# Generated by Django 4.1.6 on 2023-02-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_price", models.FloatField()),
                ("product_cat", models.CharField(max_length=100)),
                ("quantity_avaliable", models.IntegerField(default=100)),
                ("product_desc", models.CharField(max_length=500)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images"
                    ),
                ),
            ],
        ),
    ]
