# Generated by Django 4.1.6 on 2023-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name_plural": "Products"},
        ),
        migrations.AddField(
            model_name="product",
            name="product_image2",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image3",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
    ]
