# Generated by Django 4.1.6 on 2023-02-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0003_alter_product_product_cat_alter_product_product_desc_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity_avaliable",
            new_name="quantity_available",
        ),
    ]
