# Generated by Django 4.1.6 on 2023-02-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_quantity_avaliable_product_quantity_available"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="quantity_available",),
    ]
