# Generated by Django 4.1.6 on 2023-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_material_remove_product_product_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity_available",
            field=models.IntegerField(default=0),
        ),
    ]
