# Generated by Django 4.1.6 on 2023-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_product_quantity_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_material",
            field=models.ManyToManyField(
                related_name="material", to="product.material"
            ),
        ),
    ]
