# Generated by Django 4.1.6 on 2023-02-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_productmaterial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material", old_name="name", new_name="material_name",
        ),
    ]
