# Generated by Django 4.1.6 on 2023-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Credit Card", "Credit Card"),
                    ("Debit Card", "Debit Card"),
                    ("Net Banking", "Net Banking"),
                ],
                default="Credit Card",
                max_length=50,
            ),
        ),
    ]
