# Generated by Django 4.1.6 on 2023-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="quantity", field=models.IntegerField(default=1),
        ),
    ]
