# Generated by Django 4.1.6 on 2023-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(default="Visa", max_length=50),
        ),
    ]
