# Generated by Django 4.1.6 on 2023-02-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_options_product_product_image2_and_more"),
        ("review_blog", "0004_review_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="author",),
        migrations.AlterField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="product.product",
            ),
        ),
    ]
