# Generated by Django 4.1.6 on 2023-02-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review_blog", "0007_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="name",),
    ]
