# Generated by Django 4.1.6 on 2023-02-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
        ("review_blog", "0009_comment_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_auth.profile",
            ),
        ),
    ]
