# Generated by Django 4.1.2 on 2023-05-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_blog", "0012_alter_nlpreviewstored_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review", name="rating", field=models.IntegerField(default=0),
        ),
    ]
